import { Inter } from "next/font/google";
import "../globals.css";

import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children,lang }) {

  return (
    <html lang="en">
      <body className={`${inter.className} container mx-auto`}>
        <Navbar />
        <div className="container grid lg:grid-cols-[218px_1fr] gap-[3.5rem]">
          <Sidebar />
          {children}
        </div>
        <div id="modal-root-content" />
      </body>
    </html>
  );
}
